# -*- coding: utf-8 -*-
"""Model 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6_rLAFbd9nEJ167ttUVZPAGRbOk_bIm
"""

!pip install -q transformers scikit-learn pandas torch accelerate

csv_path = r"C:\Users\umaya\Downloads\archive\synthetic_liver_cancer_dataset.csv"
print('Loaded file:', csv_path)

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report,
)

MODEL_NAME = 'emilyalsentzer/Bio_ClinicalBERT'
MAX_LEN = 128
BATCH_SIZE = 16

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
if device.type != 'cuda':
    print('WARNING: no GPU detected. Go to Runtime > Change runtime type > T4 GPU.')

csv_path = r"C:\Users\umaya\Downloads\archive\synthetic_liver_cancer_dataset.csv"
print('Loaded file:', csv_path)

from google.colab import drive
drive.mount('/content/drive')

csv_path = '/content/drive/MyDrive/synthetic_liver_cancer_dataset.csv'

print(f'Loading {MODEL_NAME} ...')
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
base_model = AutoModel.from_pretrained(MODEL_NAME).to(device)
base_model.eval()
print('Model loaded.')

from google.colab import files
uploaded = files.upload()
csv_path = list(uploaded.keys())[0]
print('Loaded file:', csv_path)

print(csv_path)
import os
print(os.listdir('.'))

print(csv_path)
import os
print(os.listdir('.'))

import pandas as pd

df = pd.read_csv('synthetic_liver_cancer_dataset.csv')

def row_to_sentence(row):
    parts = []
    parts.append(f"A {row['age']}-year-old {str(row['gender']).lower()} patient")
    parts.append(f"with a BMI of {row['bmi']}")

    lifestyle = [
        f"{str(row['alcohol_consumption']).lower()} alcohol consumption",
        f"{str(row['smoking_status']).lower()} smoking status",
        f"{str(row['physical_activity_level']).lower()} physical activity level",
    ]
    parts.append("Lifestyle factors include " + ", ".join(lifestyle))

    conditions = []
    if row["hepatitis_b"] == 1: conditions.append("hepatitis B")
    if row["hepatitis_c"] == 1: conditions.append("hepatitis C")
    if row["cirrhosis_history"] == 1: conditions.append("a history of cirrhosis")
    if row["diabetes"] == 1: conditions.append("diabetes")
    if row["family_history_cancer"] == 1: conditions.append("a family history of cancer")
    if conditions:
        parts.append("Relevant medical history: " + ", ".join(conditions))
    else:
        parts.append("No significant medical history of hepatitis, cirrhosis, diabetes, or family cancer history was noted")

    parts.append(
        f"Laboratory findings show a liver function score of {row['liver_function_score']} "
        f"and an alpha-fetoprotein (AFP) level of {row['alpha_fetoprotein_level']} ng/mL"
    )
    outcome = "positive for liver cancer" if row["liver_cancer"] == 1 else "negative for liver cancer"
    parts.append(f"Diagnostic outcome: {outcome}")
    return ". ".join(parts) + "."

df['clinical_note'] = df.apply(row_to_sentence, axis=1)
df.to_csv('liver_cancer_notes.csv', index=False)
csv_path = 'liver_cancer_notes.csv'

print(f'Generated {len(df)} clinical notes.')
print('Columns now:', df.columns.tolist())
print('\nSample note:\n', df['clinical_note'].iloc[0])

import pandas as pd

df = pd.read_csv('synthetic_liver_cancer_dataset.csv')

def row_to_sentence(row):
    parts = []
    parts.append(f"A {row['age']}-year-old {str(row['gender']).lower()} patient")
    parts.append(f"with a BMI of {row['bmi']}")

    lifestyle = [
        f"{str(row['alcohol_consumption']).lower()} alcohol consumption",
        f"{str(row['smoking_status']).lower()} smoking status",
        f"{str(row['physical_activity_level']).lower()} physical activity level",
    ]
    parts.append("Lifestyle factors include " + ", ".join(lifestyle))

    conditions = []
    if row["hepatitis_b"] == 1: conditions.append("hepatitis B")
    if row["hepatitis_c"] == 1: conditions.append("hepatitis C")
    if row["cirrhosis_history"] == 1: conditions.append("a history of cirrhosis")
    if row["diabetes"] == 1: conditions.append("diabetes")
    if row["family_history_cancer"] == 1: conditions.append("a family history of cancer")
    if conditions:
        parts.append("Relevant medical history: " + ", ".join(conditions))
    else:
        parts.append("No significant medical history of hepatitis, cirrhosis, diabetes, or family cancer history was noted")

    parts.append(
        f"Laboratory findings show a liver function score of {row['liver_function_score']} "
        f"and an alpha-fetoprotein (AFP) level of {row['alpha_fetoprotein_level']} ng/mL"
    )
    outcome = "positive for liver cancer" if row["liver_cancer"] == 1 else "negative for liver cancer"
    parts.append(f"Diagnostic outcome: {outcome}")
    return ". ".join(parts) + "."

df['clinical_note'] = df.apply(row_to_sentence, axis=1)
df.to_csv('liver_cancer_notes.csv', index=False)
csv_path = 'liver_cancer_notes.csv'

print(f'Generated {len(df)} clinical notes.')
print('Columns now:', df.columns.tolist())
print('\nSample note:\n', df['clinical_note'].iloc[0])

import numpy as np
from sklearn.model_selection import train_test_split

texts = df['clinical_note'].astype(str).values
labels = df['liver_cancer'].astype(int).values
print(f'Loaded {len(texts)} notes, class balance: {np.bincount(labels)}')

X_train, X_temp, y_train, y_temp = train_test_split(
    texts, labels, test_size=0.30, random_state=42, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)
print(f'Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}')

import torch
from transformers import AutoTokenizer, AutoModel

MODEL_NAME = 'emilyalsentzer/Bio_ClinicalBERT'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
base_model = AutoModel.from_pretrained(MODEL_NAME).to(device)
base_model.eval()
print('Model loaded.')

MAX_LEN = 128
BATCH_SIZE = 16

def extract_embeddings(texts, tokenizer, model, device):
    all_embeddings = []
    with torch.no_grad():
        for i in range(0, len(texts), BATCH_SIZE):
            batch = list(texts[i:i + BATCH_SIZE])
            enc = tokenizer(batch, padding=True, truncation=True, max_length=MAX_LEN, return_tensors='pt').to(device)
            out = model(**enc)
            cls_embeddings = out.last_hidden_state[:, 0, :]
            all_embeddings.append(cls_embeddings.cpu().numpy())
            print(f'  embedded {min(i + BATCH_SIZE, len(texts))}/{len(texts)}', end='\r')
    print()
    return np.vstack(all_embeddings)

print('Extracting train embeddings...')
X_train_emb = extract_embeddings(X_train, tokenizer, base_model, device)
print('Extracting val embeddings...')
X_val_emb = extract_embeddings(X_val, tokenizer, base_model, device)
print('Extracting test embeddings...')
X_test_emb = extract_embeddings(X_test, tokenizer, base_model, device)
print('Embedding shape:', X_train_emb.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report,
)

clf = LogisticRegression(max_iter=1000, class_weight='balanced')
clf.fit(X_train_emb, y_train)

val_preds = clf.predict(X_val_emb)
print(f'[Frozen embeddings] Validation accuracy: {accuracy_score(y_val, val_preds):.3f}')

test_preds_frozen = clf.predict(X_test_emb)
print('\n=== Frozen Embeddings: Test Set Results ===')
print(f'Accuracy:  {accuracy_score(y_test, test_preds_frozen):.3f}')
print(f'Precision: {precision_score(y_test, test_preds_frozen):.3f}')
print(f'Recall:    {recall_score(y_test, test_preds_frozen):.3f}')
print(f'F1 score:  {f1_score(y_test, test_preds_frozen):.3f}')
print('\nConfusion matrix:')
print(confusion_matrix(y_test, test_preds_frozen))
print()
print(classification_report(y_test, test_preds_frozen, target_names=['No cancer', 'Cancer']))

def row_to_sentence(row):
    parts = []
    parts.append(f"A {row['age']}-year-old {str(row['gender']).lower()} patient")
    parts.append(f"with a BMI of {row['bmi']}")

    lifestyle = [
        f"{str(row['alcohol_consumption']).lower()} alcohol consumption",
        f"{str(row['smoking_status']).lower()} smoking status",
        f"{str(row['physical_activity_level']).lower()} physical activity level",
    ]
    parts.append("Lifestyle factors include " + ", ".join(lifestyle))

    conditions = []
    if row["hepatitis_b"] == 1: conditions.append("hepatitis B")
    if row["hepatitis_c"] == 1: conditions.append("hepatitis C")
    if row["cirrhosis_history"] == 1: conditions.append("a history of cirrhosis")
    if row["diabetes"] == 1: conditions.append("diabetes")
    if row["family_history_cancer"] == 1: conditions.append("a family history of cancer")
    if conditions:
        parts.append("Relevant medical history: " + ", ".join(conditions))
    else:
        parts.append("No significant medical history of hepatitis, cirrhosis, diabetes, or family cancer history was noted")

    parts.append(
        f"Laboratory findings show a liver function score of {row['liver_function_score']} "
        f"and an alpha-fetoprotein (AFP) level of {row['alpha_fetoprotein_level']} ng/mL"
    )
    # NOTE: outcome line removed on purpose -- it was leaking the label into the text
    return ". ".join(parts) + "."

df['clinical_note'] = df.apply(row_to_sentence, axis=1)
df.to_csv('liver_cancer_notes.csv', index=False)
csv_path = 'liver_cancer_notes.csv'

print('Regenerated notes without label leakage. Sample:\n')
print(df['clinical_note'].iloc[0])

texts = df['clinical_note'].astype(str).values
labels = df['liver_cancer'].astype(int).values
print(f'Loaded {len(texts)} notes, class balance: {np.bincount(labels)}')

X_train, X_temp, y_train, y_temp = train_test_split(
    texts, labels, test_size=0.30, random_state=42, stratify=labels
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)
print(f'Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}')

print('Extracting train embeddings...')
X_train_emb = extract_embeddings(X_train, tokenizer, base_model, device)
print('Extracting val embeddings...')
X_val_emb = extract_embeddings(X_val, tokenizer, base_model, device)
print('Extracting test embeddings...')
X_test_emb = extract_embeddings(X_test, tokenizer, base_model, device)
print('Embedding shape:', X_train_emb.shape)

clf = LogisticRegression(max_iter=1000, class_weight='balanced')
clf.fit(X_train_emb, y_train)

val_preds = clf.predict(X_val_emb)
print(f'[Frozen embeddings] Validation accuracy: {accuracy_score(y_val, val_preds):.3f}')

test_preds_frozen = clf.predict(X_test_emb)
print('\n=== Frozen Embeddings: Test Set Results ===')
print(f'Accuracy:  {accuracy_score(y_test, test_preds_frozen):.3f}')
print(f'Precision: {precision_score(y_test, test_preds_frozen):.3f}')
print(f'Recall:    {recall_score(y_test, test_preds_frozen):.3f}')
print(f'F1 score:  {f1_score(y_test, test_preds_frozen):.3f}')
print('\nConfusion matrix:')
print(confusion_matrix(y_test, test_preds_frozen))
print()
print(classification_report(y_test, test_preds_frozen, target_names=['No cancer', 'Cancer']))

import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

class NotesDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            str(self.texts[idx]), padding='max_length', truncation=True,
            max_length=self.max_len, return_tensors='pt',
        )
        return {
            'input_ids': enc['input_ids'].squeeze(0),
            'attention_mask': enc['attention_mask'].squeeze(0),
            'labels': torch.tensor(self.labels[idx], dtype=torch.long),
        }

train_ds = NotesDataset(X_train, y_train, tokenizer, MAX_LEN)
val_ds = NotesDataset(X_val, y_val, tokenizer, MAX_LEN)
test_ds = NotesDataset(X_test, y_test, tokenizer, MAX_LEN)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE)

print(f'Train batches: {len(train_loader)}, Val batches: {len(val_loader)}, Test batches: {len(test_loader)}')

from transformers import AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

finetune_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=2
).to(device)

EPOCHS = 3
optimizer = torch.optim.AdamW(finetune_model.parameters(), lr=2e-5)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

for epoch in range(EPOCHS):
    finetune_model.train()
    total_loss = 0
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels_batch = batch['labels'].to(device)

        outputs = finetune_model(input_ids=input_ids, attention_mask=attention_mask, labels=labels_batch)
        loss = outputs.loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(finetune_model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)

    finetune_model.eval()
    val_preds_ft, val_true_ft = [], []
    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            outputs = finetune_model(input_ids=input_ids, attention_mask=attention_mask)
            preds = torch.argmax(outputs.logits, dim=1).cpu().numpy()
            val_preds_ft.extend(preds)
            val_true_ft.extend(batch['labels'].numpy())

    val_acc = accuracy_score(val_true_ft, val_preds_ft)
    print(f'Epoch {epoch+1}/{EPOCHS} | train loss: {avg_loss:.4f} | val accuracy: {val_acc:.3f}')

finetune_model.eval()
test_preds_ft, test_true_ft = [], []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        outputs = finetune_model(input_ids=input_ids, attention_mask=attention_mask)
        preds = torch.argmax(outputs.logits, dim=1).cpu().numpy()
        test_preds_ft.extend(preds)
        test_true_ft.extend(batch['labels'].numpy())

print('=== Fine-Tuned Model: Test Set Results ===')
print(f'Accuracy:  {accuracy_score(test_true_ft, test_preds_ft):.3f}')
print(f'Precision: {precision_score(test_true_ft, test_preds_ft):.3f}')
print(f'Recall:    {recall_score(test_true_ft, test_preds_ft):.3f}')
print(f'F1 score:  {f1_score(test_true_ft, test_preds_ft):.3f}')
print('\nConfusion matrix:')
print(confusion_matrix(test_true_ft, test_preds_ft))
print()
print(classification_report(test_true_ft, test_preds_ft, target_names=['No cancer', 'Cancer']))

from transformers import pipeline

ner_pipe = pipeline(
    'ner',
    model='d4data/biomedical-ner-all',
    tokenizer='d4data/biomedical-ner-all',
    aggregation_strategy='simple',
    device=0 if device.type == 'cuda' else -1,
)

sample_notes = df['clinical_note'].iloc[:5].tolist()
for i, note in enumerate(sample_notes):
    print(f'--- Note {i} ---')
    print(note)
    entities = ner_pipe(note)
    for ent in entities:
        print(f"  entity: '{ent['word']}'  label: {ent['entity_group']}  score: {ent['score']:.2f}")
    print()

def extract_entities_batch(notes, ner_pipe):
    results = []
    for i, note in enumerate(notes):
        ents = ner_pipe(note)
        results.append('; '.join(f"{e['word']}:{e['entity_group']}" for e in ents))
        if i % 200 == 0:
            print(f'  NER on {i}/{len(notes)}', end='\r')
    print()
    return results

df['extracted_entities'] = extract_entities_batch(df['clinical_note'].tolist(), ner_pipe)
df.to_csv('liver_cancer_notes_with_entities.csv', index=False)
print('Saved liver_cancer_notes_with_entities.csv')
df[['clinical_note', 'extracted_entities']].head()

import numpy as np

np.savez(
    'clinical_text_embeddings.npz',
    X_train=X_train_emb, y_train=y_train,
    X_val=X_val_emb, y_val=y_val,
    X_test=X_test_emb, y_test=y_test,
)
print('Saved clinical_text_embeddings.npz')

finetune_model.save_pretrained('clinicalbert_finetuned')
tokenizer.save_pretrained('clinicalbert_finetuned')
print('Saved fine-tuned model to clinicalbert_finetuned/')

from google.colab import files
files.download('clinical_text_embeddings.npz')
files.download('liver_cancer_notes_with_entities.csv')

import os
print(os.path.exists('liver_cancer_notes_with_entities.csv'))
print(os.path.exists('clinical_text_embeddings.npz'))
print(os.path.exists('clinicalbert_finetuned'))